refactor!: builds version 0.2.0
edudip/chartist-plugin-tooltip pull request #1
Opened 2022-12-06 14:58 UTC by aborrmann

2022-12-13 12:37 UTC, mariusziemke requested changes
Version bump?

2022-12-13 12:37 UTC, mariusziemke commented on src/scripts/chartist-plugin-tooltip.js
> +	    const chartType = chart.constructor.name;
even more indentation?

2022-12-13 12:48 UTC, aborrmann commented on src/scripts/chartist-plugin-tooltip.js
> +	    const chartType = chart.constructor.name;
no more indentation!

2022-12-16 08:09 UTC, dhoeferboi approved these changes

2022-12-16 11:11 UTC, mariusziemke approved these changes

2022-12-16 11:27 UTC, merged